"""Add category and ingredients to menu items

Revision ID: 9fe3f34eb1e3
Revises: ee63b00d41e7
Create Date: 2026-10-09 21:19:43.845310

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9fe3f34eb1e3'
down_revision = 'ee63b00d41e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('menu_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('ingredients', sa.JSON(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('menu_items', schema=None) as batch_op:
        batch_op.drop_column('ingredients')
        batch_op.drop_column('category')

    # ### end Alembic commands ###
